# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Publish to NPM

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: yarn
      #- run: npm test

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          always-auth: true
          node-version: 16
          registry-url: https://registry.npmjs.org/
          scope: '@icetee'
      - run: |
          echo "$(jq '.name = "@icetee/react-image-lightbox"' package.json)" > package.json
      - run: yarn
      - run: yarn run build
      - run: npm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
